apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-manager-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship-manager-database
  template:
    metadata:
      labels:
        app: ship-manager-database
    spec:
      containers:
        - image: mongo
          name: ship-manager-database
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 512m
              memory: 512Mi
          ports:
            - containerPort: 27017
              name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: ship-manager-database
spec:
  selector:
    app: ship-manager-database
  ports:
    - port: 27017
      targetPort: mongodb
